# Generated by Django 4.2.2 on 2023-07-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Negocio', 'Negocio'), ('Público', 'Público')], max_length=30),
        ),
    ]
